### PR TITLE
Add GHIssue, GHLabel, GHMilestone and extend GHRepo

### PR DESCRIPTION
**Pull request by wilzbach**
Yet another step at making the GH API more general-purpose (more PRs to come)
This basically just adds more type serialization.

### CODE REVIEW

**Comment by CyberShadow** [comment]
Question, what happens when a field is added by GitHub? Will it just not be deserialized?

**Comment by wilzbach** [comment]
> Will it just not be deserialized?

Yep as currently (we only parse about half of the payload).

**Comment by wilzbach** [comment]
Merging as this just adds improves out GH API mapping and brings us one step closer to a extracting `github_api` into a separate package ;-)

**Comment by ZombineDev** [comment]
BTW I reviewed the code a couple of weeks ago, don't know what happened with my approval. Probably lost in the > 300 open tabs I have on my PC and phone combined :D

**Pull request merged**
