### PR TITLE
Fix #92 - Use Markdown instead of HTML in greeter message

### LINKED ISSUE #92: Use Markdown instead of HTML in greeter message
After making a PR, the email I get from GitHub with @dlang-bot's automatic comment looks like this:

I suggest using Markdown instead of HTML unless absolutely necessary, so that the email appears more readable in email clients configured or limited to displaying text/plain parts over text/html.

### PR DESCRIPTION
**Pull request by wilzbach**
See https://github.com/dlang-bots/dlang-bot/issues/92

### CODE REVIEW

**Comment by CyberShadow** [comment]
This isn't even a delimited string. You can easily break it up with 
```
...bla bla bla ` ~
`bla bla bla ...
```

**Comment by CyberShadow** [comment]
Thanks for the quick fix anyhow :)

**Comment by wilzbach** [comment]
> This isn't even a delimited string. You can easily break it up with

But that looks ugly too ;-)
As said, I simply didn't realize that using HTML is a  problem. Sorry.

**Comment by wilzbach** [comment]
> Thanks for the quick fix anyhow :)

You are very welcome.
FYI: The Bot is auto-deployed on Heroku, but deployment takes a bit because Heroku waits until the respective Travis builds for master have successfully passed - though it should be live in ~10-15 minutes ;-)

**Pull request merged**
