### PR TITLE
use command line argument to run daily cron tasks

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by MartinNowak** [comment]
Weirdly enough breaks unrelated trello tests, apparently because of some parse failure of the bug refs in comments (detecting fixed as false).
Almost looks like a memory corruption or so.
Maybe we should use a little less range chaining there?

**Comment by wilzbach** [comment]
> Almost looks like a memory corruption or so.

Hmm, if I set the log-level to debug, the errors goes away:

```
setLogLevel(LogLevel.debug_);
```

Also this patch moves the error to the next test:

```
diff --git a/test/utils.d b/test/utils.d
index 6740430..d5e2091 100644
--- a/test/utils.d
+++ b/test/utils.d
@@ -123,9 +127,12 @@ auto payloadServer(scope HTTPServerRequest req, scope HTTPServerResponse res)
             if (expectation.jsonHandler !is null)
                 expectation.jsonHandler(payloadJson);
 
-            payload = payloadJson.toString;
+            return res.writeJsonBody(payloadJson);
+        }
+        else
+        {
+            return res.writeBody(payload);
         }
-        return res.writeBody(payload);
     }
 }
```

**Comment by wilzbach** [comment]
> Almost looks like a memory corruption or so.

It seems it's more a multi-threading issue in our test script ...

-> the cruel `__gshared` and `synchronized` seem to work fine :)

**Comment by wilzbach** [comment]
Hmm LDC doesn't seem to like it:

image

**Comment by wilzbach** [comment]
But ldc-beta does work:

image

**Comment by wilzbach** [comment]
LDC is broken in #78 as well:

image

So I am giving this a go & deploying it.

**Comment by wilzbach** [comment]
Activated the scheduler: https://scheduler.heroku.com/dashboard

**Pull request merged**
