### PR TITLE
Explain that mentioning multiple issues is possible

### PR DESCRIPTION
**Pull request by wilzbach**
It seems that many people aren't aware of this ...

### CODE REVIEW

**Comment by ZombineDev** [comment]
I changed "fixes Issues" to "Fixes issues" as that way it looks better to me, I hope you don't mind @wilzbach.

**Comment by wilzbach** [comment]
Sure, but unfortunately due to a regression in dmd-beta our build is broken. Overwriting it for this one.

**Comment by ZombineDev** [comment]
> Overwriting it for this one.

Of course.

> Sure, but unfortunately due to a regression in dmd-beta our build is broken.

That's very strange, because it doesn't seem to be a problem with dmd-nightly.
I get the same error with this code:
```D
void main()
{
    class C {}
    auto i = typeid(C).init[];
}
```

```
(dmd-master-2017-07-05)/mnt/d/tmp_code/bug_test
$ dmd -o- test_typeinfo_squarebrackets.d
test_typeinfo_squarebrackets.d(4): Error: no [] operator overload for type object.TypeInfo_Class
```

Even in vibe-d-0.7.31-rc.2 this [error](https://travis-ci.org/dlang-bots/dlang-bot/jobs/250674662#L211) seems to be worked [around](https://github.com/rejectedsoftware/vibe.d/blob/v0.7.31-rc.2/source/vibe/utils/memory.d#L843-L846). So I have no idea what's going on.

---

Edit: I found by myself out exactly what @CyberShadow did in https://issues.dlang.org/show_bug.cgi?id=17608 -> `__VERSION__` got changed from 2075 to 75.

**Comment by wilzbach** [comment]
> Edit: I found by myself out exactly what @CyberShadow did in https://issues.dlang.org/show_bug.cgi?id=17608 -> __VERSION__ got changed from 2075 to 75.

Sorry for not linking to the issue directly (I was on my phone).

**Pull request merged**
