### PR TITLE
Don't treat major issues as regressions

### PR DESCRIPTION
**Pull request by wilzbach**

### CODE REVIEW

**Comment by ZombineDev** [comment]
Rebased

**Comment by ZombineDev** [comment]
Added a commit to allow dmd-nightly and dmd-beta to fail until we fix the issue there.

**Comment by ZombineDev** [comment]
@wilzbach FYI, for some reason dlang-bot didn't auto-merge himself.

**Comment by wilzbach** [comment]
hmm that's all I see in the logs:

image

**Comment by wilzbach** [comment]
Okay digged a bit deeper:

```
28 Dec 2017 11:53:05.962220 <190>1 2017-12-28T10:53:05.666150+00:00 app web.1 - - [35A0FFE0:2CECDFE0 WRN] PUT https://api.github.com/repos/dlang-bots/dlang-bot/pulls/152/merge failed; Method Not Allowed 405.
28 Dec 2017 11:53:06.047285 <190>1 2017-12-28T10:53:05.666167+00:00 app web.1 - - [35A0FFE0:2CECDFE0 WRN] {"message":"Required status check \"continuous-integration/travis-ci/pr\" is pending.","documentation_url":"https://help.github.com/articles/about-protected-branches"}
28 Dec 2017 11:53:07.404306 <158>1 2017-12-28T10:53:05.042982+00:00 heroku router - - at=info method=POST path="/github_hook" host=dlang-bot.herokuapp.com request_id=b0ccf261-04e6-42d8-b590-70354f1f63c0 fwd="192.30.252.37" dyno=web.1 connect=1ms service=47ms status=200 bytes=145 protocol=https
28 Dec 2017 11:53:13.659204 <190>1 2017-12-28T10:53:13.368053+00:00 app web.1 - - [35A0FFE0:2CECDFE0 CRITICAL] Task terminated with uncaught exception: Got JSON of type null_, expected string.
28 Dec 2017 11:53:13.660211 <190>1 2017-12-28T10:53:13.382247+00:00 app web.1 - - [35A0FFE0:2CECDFE0 dbg] Full error: std.json.JSONException@std/json.d(1196): Got JSON of type null_, expected string.
28 Dec 2017 11:53:13.660134 <190>1 2017-12-28T10:53:13.382253+00:00 app web.1 - - [35A0FFE0:2CECDFE0 dbg] ----------------
28 Dec 2017 11:53:13.660244 <190>1 2017-12-28T10:53:13.382254+00:00 app web.1 - - [35A0FFE0:2CECDFE0 dbg] ??:? const(pure @safe void function(immutable(char)[])) vibe.data.json.Json.checkType!(immutable(char)[]).checkType [0x8a3fa1]
28 Dec 2017 11:53:13.660443 <190>1 2017-12-28T10:53:13.382264+00:00 app web.1 - - [35A0FFE0:2CECDFE0 dbg] ??:? @safe void vibe.data.serialization.__T20deserializeValueImplTS4vibe4data4json14JsonSerializerS404vibe4data13serialization13DefaultPolicyZ.deserializeValueDeduced!(dlangbot.github_api.GHIssue).deserializeValueDeduced(ref vibe.data.json.JsonSerializer).__lambda2!(immutable(char)[]).__lambda2(immutable(char)[]) [0x909279]
28 Dec 2017 11:53:13.660388 <190>1 2017-12-28T10:53:13.382269+00:00 app web.1 - - [35A0FFE0:2CECDFE0 dbg] ??:? _D4vibe4data4json14JsonSerializer141__T14readDictionaryTS4vibe4data13serialization85__T6TraitsTS8dlangbot10github_api7GHIssueS404vibe4data13serialization13DefaultPolicyZ6TraitsZ14readDictionaryMFMDFNfAyaZvZ14__foreachbody3MFNfKAyaKS4vibe4data4json4JsonZi [0x909545]
28 Dec 2017 11:53:13.660143 <190>1 2017-12-28T10:53:13.382275+00:00 app web.1 - - [35A0FFE0:2CECDFE0 dbg] ??:? _aaApply2 [0xa77104]
28 Dec 2017 11:53:13.660369 <190>1 2017-12-28T10:53:13.382283+00:00 app web.1 - - [35A0FFE0:2CECDFE0 dbg] ??:? @safe void vibe.data.json.JsonSerializer.readDictionary!(vibe.data.serialization.__T6TraitsTS8dlangbot10github_api7GHIssueS404vibe4data13serialization13DefaultPolicyZ.Traits).readDictionary(scope @safe void delegate(immutable(char)[])) [0x909483]
28 Dec 2017 11:53:13.660407 <190>1 2017-12-28T10:53:13.382302+00:00 app web.1 - - [35A0FFE0:2CECDFE0 dbg] ??:? @safe dlangbot.github_api.GHIssue vibe.data.serialization.__T20deserializeValueImplTS4vibe4data4json14JsonSerializerS404vibe4data13serialization13DefaultPolicyZ.deserializeValueDeduced!(dlangbot.github_api.GHIssue).deserializeValueDeduced(ref vibe.data.json.JsonSerializer) [0x908880]
28 Dec 2017 11:53:13.660393 <190>1 2017-12-28T10:53:13.382317+00:00 app web.1 - - [35A0FFE0:2CECDFE0 dbg] ??:? @safe dlangbot.github_api.GHIssue vibe.data.serialization.__T20deserializeValueImplTS4vibe4data4json14JsonSerializerS404vibe4data13serialization13DefaultPolicyZ.deserializeValue!(dlangbot.github_api.GHIssue).deserializeValue(ref vibe.data.json.JsonSerializer) [0x90881a]
28 Dec 2017 11:53:13.661398 <190>1 2017-12-28T10:53:13.382319+00:00 app web.1 - - [35A0FFE0:2CECDFE0 dbg] ??:? @safe void vibe.data.serialization.__T20deserializeValueImplTS4vibe4data4json14JsonSerializerS404vibe4data13serialization13DefaultPolicyZ.deserializeValueDeduced!(dlangbot.github_api.GHIssue[]).deserializeValueDeduced(ref vibe.data.json.JsonSerializer).__lambda3() [0x9085ed]
28 Dec 2017 11:53:13.661377 <190>1 2017-12-28T10:53:13.382334+00:00 app web.1 - - [35A0FFE0:2CECDFE0 dbg] ??:? @safe void vibe.data.json.JsonSerializer.readArray!(vibe.data.serialization.__T6TraitsTAS8dlangbot10github_api7GHIssueS404vibe4data13serialization13DefaultPolicyZ.Traits).readArray(scope @safe void delegate(ulong), scope @safe void delegate()) [0x908777]
28 Dec 2017 11:53:13.661411 <190>1 2017-12-28T10:53:13.382349+00:00 app web.1 - - [35A0FFE0:2CECDFE0 dbg] ??:? @safe dlangbot.github_api.GHIssue[] vibe.data.serialization.__T20deserializeValueImplTS4vibe4data4json14JsonSerializerS404vibe4data13serialization13DefaultPolicyZ.deserializeValueDeduced!(dlangbot.github_api.GHIssue[]).deserializeValueDeduced(ref vibe.data.json.JsonSerializer) [0x90858e]
28 Dec 2017 11:53:13.661358 <190>1 2017-12-28T10:53:13.382353+00:00 app web.1 - - [35A0FFE0:2CECDFE0 dbg] ??:? std.algorithm.iteration.__T10UniqResultS568dlangbot6github18getIssuesForLabelsFAyaxAAyaZ9__lambda4TAS8dlangbot10github_api7GHIssueZ.UniqResult dlangbot.github.getIssuesForLabels(immutable(char)[], const(immutable(char)[][])) [0x91e29a]
28 Dec 2017 11:53:13.661195 <190>1 2017-12-28T10:53:13.382368+00:00 app web.1 - - [35A0FFE0:2CECDFE0 dbg] ??:? void dlangbot.github.searchForAutoMergePrs(immutable(char)[]) [0x91e369]
28 Dec 2017 11:53:13.661212 <190>1 2017-12-28T10:53:13.382381+00:00 app web.1 - - [35A0FFE0:2CECDFE0 dbg] ??:? _D8dlangbot5utils22__T9ThrottlerTPFAyaZvZ9Throttler6opCallMFAyaZ9__lambda3MFZv [0x946219]
28 Dec 2017 11:53:13.661226 <190>1 2017-12-28T10:53:13.382396+00:00 app web.1 - - [35A0FFE0:2CECDFE0 dbg] ??:? @trusted void vibe.core.core.setTimer(core.time.Duration, void delegate(), bool).__lambda4() [0xa012f3]
28 Dec 2017 11:53:13.661281 <190>1 2017-12-28T10:53:13.382398+00:00 app web.1 - - [35A0FFE0:2CECDFE0 dbg] ??:? void vibe.core.core.makeTaskFuncInfo!(@safe void delegate()).makeTaskFuncInfo(ref @safe void delegate()).callDelegate(vibe.core.core.TaskFuncInfo*) [0xa54893]
28 Dec 2017 11:53:13.661168 <190>1 2017-12-28T10:53:13.382412+00:00 app web.1 - - [35A0FFE0:2CECDFE0 dbg] ??:? void vibe.core.core.CoreTask.run() [0xa0186b]
28 Dec 2017 11:53:13.661162 <190>1 2017-12-28T10:53:13.382418+00:00 app web.1 - - [35A0FFE0:2CECDFE0 dbg] ??:? void core.thread.Fiber.run() [0xacd8b9]
28 Dec 2017 11:53:13.661150 <190>1 2017-12-28T10:53:13.382426+00:00 app web.1 - - [35A0FFE0:2CECDFE0 dbg] ??:? fiber_entryPoint [0xacd5f7]
28 Dec 2017 11:53:13.734135 <190>1 2017-12-28T10:53:13.382434+00:00 app web.1 - - [35A0FFE0:2CECDFE0 dbg] ??:? [0xffffffff]
```

Not the exception is "unrelated" as it just crashes while processing the GitHub reponse
So I'm not sure why it didn't receive the Travis notification - or maybe it did and GitHub wasn't fast enough and said "no"?

**Pull request merged**
